# Usar uma imagem base de Python
FROM python:3.9-slim

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos de requisitos para o container
COPY requirements.txt ./

# Instalar as dependências da aplicação
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo o código da aplicação para o container
COPY . .

# Expor a porta que sua aplicação usa (ajuste se for necessário)
EXPOSE 5000

# Comando para rodar a aplicação (ajuste se for necessário)
CMD ["python", "app.py"]
